# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs: 
    - images

default_config:

http:
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem
  base_url: !secret ssldns_base_url

  
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret zwave_network_key

wemo:
  discovery: false
  static:
    - !secret wemo_smart_switch
    - !secret wemo_mini_1_switch


tplink:
  discovery: true
  switch:
    - host: !secret kasa_switch_1
    - host: !secret kasa_switch_2
    - host: !secret kasa_switch_3
    - host: !secret kasa_switch_4


#wink:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate


# Includes
group: !include groups.yaml
#automation: !include automations.yaml
script: !include scripts.yaml
#scene: !include scenes.yaml
#light: !include lights.yaml
#camera: !include cameras.yaml

