# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  packages: !include_dir_named packages

default_config:

http:
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem
  base_url: !secret ssldns_base_url

  
zwave:
  usb_path: /dev/ttyACM0


#wink:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate


# Includes
group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml
#light: !include lights.yaml
#camera: !include cameras.yaml

