climate honeywell:
# Example configuration.yaml entry
  - platform: honeywell
    username: !secret honeywell_username
    password: !secret honeywell_password
    region: us


sensor:
  - platform: template
    sensors:
      current_temperature:
        friendly_name: 'Current Temperature'
        value_template: "{{ state_attr('climate.sun_room' , 'current_temperature') }}"