climate honeywell:
# Example configuration.yaml entry
  - platform: honeywell
    username: !secret honeywell_username
    password: !secret honeywell_password
    region: us


sensor:
  - platform: template
    sensors:
      upstairs_temperature:
        friendly_name: upstairs temp
        value_template: "{{ state_attr('climate.sun_room', 'current_temperature') }}"
        unit_of_measurement: F

      upstairs_humitity:
        friendly_name: upstairs humitity
        value_template: "{{ state_attr('climate.sun_room', 'current_humidity') }}"
        unit_of_measurement: "%"