wake_on_lan:

media_player:
  - platform: webostv
    host: !secret tv_lgtv_ip_address
    name: Living Room TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_lgtv_mac_address

    customize:
      sources:
        - HDMI 2
        - Amazon Prime Video
        - YouTube
        - makotv
        - Netflix
        - Disney Plus
        - TV Guide
        - TV Scheduler
        - HDMI 1
        
notify:
  - platform: webostv
    host: !secret tv_lgtv_ip_address
    name: livingroom_tv
    filename: webostv.conf
        
sensor:
  - platform: template
    sensors:
      living_room_tv_source:
        entity_id:
          - media_player.living_room_tv
        value_template: "{{ states.media_player.living_room_tv.attributes.source }}"
        friendly_name: 'Living Room TV Source'
        
        
        
        
  - platform: onkyo
    host: !secret onkyo_ip_address
    name: receiver