homeassistant:
  customize:
    media_player.ht_rc560_0009b0926861:
      friendly_name: Onkyo-HT-RC560


media_player:

  - platform: onkyo
  #  host: !secret onkyo_ip_address
  #  name: receiver


alexa_media:
  accounts:
    - email: !secret amz_email
      password: !secret amz_passw
      url: alexa.amazon.com