sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time_iso'
      - 'time_utc'
      - beat


  - platform: template
    sensors:
      template_last_motion:
        friendly_name: 'Last Motion'
        value_template: >
          {%- set sensors = [states.sensor.sensor.nodeid_5_alarm_home_security_2 , states.sensor.nodeid_5_alarm_home_security_2  ] %}
          {% for sensor in sensors %}
            {% if as_timestamp(sensor.lastUpdate) == as_timestamp(sensors | map(attribute='lastUpdate') | max) %}
              {{ sensor.name }}
            {% endif %}
          {% endfor %}
