sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time_iso'
      - 'time_utc'
      - beat


  - platform: template
    sensors:
      template_last_motion:
        friendly_name: 'Last Motion'
        value_template: >
          {%- set sensors = [states.sensor.livingroom_sensor_burglar , states.sensor.office_burglar_sensor  ] %}
          {% for sensor in sensors %}
            {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
              {{ sensor.name }}
            {% endif %}
          {% endfor %}
